id: alien4cloud-mock-paas-provider
name: Mock PaaS provider
version: ${project.version}
description: >
  Plugin that contains a single paas provider for deployments' mocking.
configuration_class: alien4cloud.plugin.mock.MockPaaSProviderPluginConfiguration
component_descriptors:
  - bean_name: mock-orchestrator-factory
    name: Mock Orchestrator Factory
    description: >
      Orchestrator Factory that instanciate orchestrators that just mocks deployment.
      Used for our automated tests the plugin suceed for every application except an application named:
       - BAD-APPLICATION: The deployment will fail.
       - WARN-APPLICATION: The deployment will ends up in a warning state.
  - bean_name: mock-anti-affinity-modifier
    name: Mock Anti affinity modifier
    description: >
      Sample implementation of an anti-affinity policy through an alien modifier that will inject zones into compute nodes.
  - bean_name: mock-fake-modifier
    name: Mock fake modifier
    description: >
      Fake modifier used for the test.
#  - bean_name: mock-location-matcher
#    name: Mock location matcher
#    description: >
#      A location matcher that matches a topology against locations based on some properties.
#      It'll only matches locations managed by orchestrators from the mock-orchestrator-factory
#       - BAD-APPLICATION: The deployment will fail.
#       - WARN-APPLICATION: The deployment will ends up in a warning state.            
